export enum IconType {
  Linkedin = "Linkedin",
  Github = "Github",
  Mail = "Mail",
  TailwindCSS = "TailwindCSS",
  TypeScript = "TypeScript",
  NextJS = "Next.js",
  Web = "Website access",
  ThreeJS = "Three.js",
  GermanFlag = "German",
  SpanishFlag = "Spanish",
  UKFlag = "English",
  NodeJS = "Node.js",
  DotNet = ".NET",
  Java = "Java",
  C = "C",
  SQLDeveloper = "SQLDeveloper",
  Python = "Python",
  JavaScript = "JavaScript",
  CSS = "CSS",
  HTML = "HTML",
  Info = "Info",
}
